import { CropData, makeGTCrop } from './Database.js';

CropData.registerCrop(makeGTCrop({
    name: "Indigo",
    tier: 2,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 1,
    attributeChemical: 1,
    attributeFood: 1,
    attributeDefensive: 0,
    attributeColor: 4,
    attributeWeed: 0,
    attributes: ["Flower", "Blue", "Ingredient"],
    defaultDrop: "Indigo Blossom",
}));

CropData.registerCrop(makeGTCrop({
    name: "Flax",
    tier: 2,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 1,
    attributeFood: 1,
    attributeDefensive: 2,
    attributeColor: 0,
    attributeWeed: 1,
    attributes: ["Silk", "Tendrilly", "Adictive"],
    defaultDrop: "String",
}));

CropData.registerCrop(makeGTCrop({
    name: "Oilberries",
    tier: 9,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 6,
    attributeFood: 1,
    attributeDefensive: 2,
    attributeColor: 1,
    attributeWeed: 12,
    attributes: ["Fire", "Dark", "Reed", "Rotten", "Coal", "Oil"],
    defaultDrop: "Oil Berry",
}));

CropData.registerCrop(makeGTCrop({
    name: "Bobsyeruncleranks",
    tier: 11,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 4,
    attributeFood: 0,
    attributeDefensive: 8,
    attributeColor: 2,
    attributeWeed: 9,
    attributes: ["Shiny", "Tendrilly", "Emerald", "Berylium", "Crystal"],
    defaultDrop: "Bobs-Yer-Uncle-Berry",
    specialDrops: ["Emerald"],
}));

CropData.registerCrop(makeGTCrop({
    name: "Diareed",
    tier: 12,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 5,
    attributeFood: 0,
    attributeDefensive: 10,
    attributeColor: 2,
    attributeWeed: 10,
    attributes: ["Fire", "Shiny", "Reed", "Coal", "Diamond", "Crystal"],
    foundationBlock: "Diamond Block or Diamond Ore",
    defaultDrop: "Diamond Dust",
    specialDrops: ["Diamond"],
}));

CropData.registerCrop(makeGTCrop({
    name: "Withereed",
    tier: 8,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 2,
    attributeFood: 0,
    attributeDefensive: 4,
    attributeColor: 1,
    attributeWeed: 3,
    attributes: ["Fire", "Undead", "Reed", "Coal", "Rotten", "Wither"],
    foundationBlock: "Coal Block or Coal Ore",
    defaultDrop: "Coal Dust",
    specialDrops: ["Coal"],
}));

CropData.registerCrop(makeGTCrop({
    name: "Blazereed",
    tier: 6,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 0,
    attributeFood: 4,
    attributeDefensive: 1,
    attributeColor: 0,
    attributeWeed: 0,
    attributes: ["Fire", "Blaze", "Reed", "Sulfur"],
    defaultDrop: "Blaze Powder",
    specialDrops: ["Blaze Rod"],
}));

CropData.registerCrop(makeGTCrop({
    name: "Eggplant",
    tier: 6,
    maxSize: 3,
    growthStageAfterHarvest: 2,
    minimumHarvestSize: 3,
    attributeChemical: 0,
    attributeFood: 4,
    attributeDefensive: 1,
    attributeColor: 0,
    attributeWeed: 0,
    attributes: ["Chicken", "Egg", "Food", "Feather", "Flower", "Addictive"],
    defaultDrop: "Egg",
    specialDrops: ["Raw Chicken", "Feather", "Feather", "Feather"],
}));

CropData.registerCrop(makeGTCrop({
    name: "Corium",
    tier: 6,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 0,
    attributeFood: 2,
    attributeDefensive: 3,
    attributeColor: 1,
    attributeWeed: 0,
    attributes: ["Cow", "Silk", "Tendrilly"],
    defaultDrop: "Leather",
}));

CropData.registerCrop(makeGTCrop({
    name: "Corpseplant",
    tier: 5,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 0,
    attributeFood: 2,
    attributeDefensive: 1,
    attributeColor: 0,
    attributeWeed: 3,
    attributes: ["Toxic", "Undead", "Tendrilly", "Food", "Rotten"],
    defaultDrop: "Rotten Flesh",
    specialDrops: ["Bone Meal", "Bone Meal", "Bone"],
}));

CropData.registerCrop(makeGTCrop({
    name: "Creeperweed",
    tier: 7,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 3,
    attributeFood: 0,
    attributeDefensive: 5,
    attributeColor: 1,
    attributeWeed: 3,
    attributes: ["Creeper", "Tendrilly", "Explosive", "Fire", "Sulfur", "Saltpeter", "Coal"],
    defaultDrop: "Gunpowder",
}));

CropData.registerCrop(makeGTCrop({
    name: "Enderbloom",
    tier: 10,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 5,
    attributeFood: 0,
    attributeDefensive: 2,
    attributeColor: 1,
    attributeWeed: 6,
    attributes: ["Ender", "Flower", "Shiny"],
    defaultDrop: "Enderpearl Dust",
    specialDrops: ["Ender Pearl", "Ender Pearl", "Ender Eye"],
}));

CropData.registerCrop(makeGTCrop({
    name: "Meatrose",
    tier: 7,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 0,
    attributeFood: 4,
    attributeDefensive: 1,
    attributeColor: 3,
    attributeWeed: 0,
    attributes: ["Food", "Flower", "Cow", "Fish", "Chicken", "Pig"],
    defaultDrop: "Pink Dye",
    specialDrops: ["Raw Beef", "Raw Porkchop", "Raw Chicken", "Raw Fish"],
}));
CropData.registerCrop(makeGTCrop({
    name: "Milkwart",
    tier: 6,
    maxSize: 3,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 3,
    attributeChemical: 0,
    attributeFood: 3,
    attributeDefensive: 0,
    attributeColor: 1,
    attributeWeed: 0,
    attributes: ["Food", "Milk", "Cow"],
    defaultDrop: "Milk Wart",
}));

CropData.registerCrop(makeGTCrop({
    name: "Slimeplant",
    tier: 6,
    maxSize: 4,
    growthStageAfterHarvest: 3,
    minimumHarvestSize: 4,
    attributeChemical: 3,
    attributeFood: 0,
    attributeDefensive: 0,
    attributeColor: 0,
    attributeWeed: 2,
    attributes: ["Slime", "Bouncy", "Sticky", "Bush"],
    defaultDrop: "Slimeball",
}));

CropData.registerCrop(makeGTCrop({
    name: "Spidernip",
    tier: 4,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 2,
    attributeFood: 1,
    attributeDefensive: 4,
    attributeColor: 1,
    attributeWeed: 3,
    attributes: ["Toxic", "Silk", "Spider", "Flower", "Ingredient", "Addictive"],
    defaultDrop: "String",
    specialDrops: ["Spider Eye", "Cobweb"],
}));

CropData.registerCrop(makeGTCrop({
    name: "Tearstalks",
    tier: 8,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 1,
    attributeFood: 2,
    attributeDefensive: 0,
    attributeColor: 0,
    attributeWeed: 0,
    attributes: ["Healing", "Nether", "Ingredient", "Reed", "Ghast"],
    defaultDrop: "Ghast Tear",
}));

CropData.registerCrop(makeGTCrop({
    name: "Tine",
    tier: 5,
    maxSize: 3,
    growthStageAfterHarvest: 2,
    minimumHarvestSize: 3,
    attributeChemical: 2,
    attributeFood: 0,
    attributeDefensive: 3,
    attributeColor: 0,
    attributeWeed: 0,
    attributes: ["Shiny", "Metal", "Pine", "Tin", "Bush"],
    foundationBlock: "Tin Block or Tin Ore",
    defaultDrop: "Tine Twig",
}));

CropData.registerCrop(makeGTCrop({
    name: "Coppon",
    tier: 6,
    maxSize: 3,
    growthStageAfterHarvest: 2,
    minimumHarvestSize: 3,
    attributeChemical: 2,
    attributeFood: 0,
    attributeDefensive: 1,
    attributeColor: 1,
    attributeWeed: 1,
    attributes: ["Shiny", "Metal", "Cotton", "Copper", "Bush"],
    foundationBlock: "Copper Block or Copper Ore",
    defaultDrop: "Coppon Fiber",
}));

CropData.registerCrop(makeGTCrop({
    name: "Brown Mushrooms (GT)",
    tier: 1,
    maxSize: 3,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 3,
    attributeChemical: 0,
    attributeFood: 2,
    attributeDefensive: 0,
    attributeColor: 0,
    attributeWeed: 2,
    attributes: ["Food", "Mushroom", "Ingredient"],
    defaultDrop: "Brown Mushroom", // The in-game name is just "Mushroom"
}));

CropData.registerCrop(makeGTCrop({
    name: "Red Mushrooms (GT)",
    tier: 1,
    maxSize: 3,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 3,
    attributeChemical: 0,
    attributeFood: 1,
    attributeDefensive: 3,
    attributeColor: 0,
    attributeWeed: 2,
    attributes: ["Toxic", "Mushroom", "Ingredient"],
    defaultDrop: "Red Mushroom", // The in-game name is just "Mushroom"
}));

CropData.registerCrop(makeGTCrop({
    name: "Argentia",
    tier: 7,
    maxSize: 4,
    growthStageAfterHarvest: 3,
    minimumHarvestSize: 4,
    attributeChemical: 2,
    attributeFood: 0,
    attributeDefensive: 1,
    attributeColor: 0,
    attributeWeed: 0,
    attributes: ["Shiny", "Metal", "Silver", "Reed"],
    foundationBlock: "Silver Block or Silver Ore",
    defaultDrop: "Argentia Leaf",
}));

CropData.registerCrop(makeGTCrop({
    name: "Plumbilia",
    tier: 6,
    maxSize: 4,
    growthStageAfterHarvest: 3,
    minimumHarvestSize: 4,
    attributeChemical: 2,
    attributeFood: 0,
    attributeDefensive: 3,
    attributeColor: 1,
    attributeWeed: 1,
    attributes: ["Heavy", "Metal", "Lead", "Reed"],
    foundationBlock: "Lead Block or Lead Ore",
    defaultDrop: "Plumbilia Leaf",
}));

CropData.registerCrop(makeGTCrop({
    name: "Steeleafranks",
    tier: 10,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 3,
    attributeFood: 0,
    attributeDefensive: 7,
    attributeColor: 2,
    attributeWeed: 8,
    attributes: ["Metal", "Tendrilly", "Iron"],
    defaultDrop: "Steeleaf Dust",
    specialDrops: ["Steeleaf"],
}));

CropData.registerCrop(makeGTCrop({
    name: "Liveroots",
    tier: 8,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 2,
    attributeFood: 0,
    attributeDefensive: 5,
    attributeColor: 2,
    attributeWeed: 6,
    attributes: ["Wood", "Tendrilly"],
    defaultDrop: "Liveroot Dust",
    specialDrops: ["Liveroot"],
}));

CropData.registerCrop(makeGTCrop({
    name: "Trollplant",
    tier: 6,
    maxSize: 5,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 0,
    attributeFood: 0,
    attributeDefensive: 5,
    attributeColor: 2,
    attributeWeed: 8,
    attributes: ["Troll", "Bad", "Scrap"],
    defaultDrop: "Ruby (fake)", // The in-game name is just "Ruby"
    specialDrops: ["Plantball", "Scrap", "Plutonium 241 Dust"],
}));

CropData.registerCrop(makeGTCrop({
    name: "Lazulia",
    tier: 7,
    maxSize: 4,
    growthStageAfterHarvest: 2,
    minimumHarvestSize: 4,
    attributeChemical: 4,
    attributeFood: 2,
    attributeDefensive: 5,
    attributeColor: 7,
    attributeWeed: 4,
    attributes: ["Shiny", "Bad", "Crystal", "Lapis"],
    foundationBlock: "Lapis Lazuli Block or Lapis Lazuli Ore",
    defaultDrop: "Lapis Dust",
}));

CropData.registerCrop(makeGTCrop({
    name: "Glowheat",
    tier: 10,
    maxSize: 7,
    growthStageAfterHarvest: 5,
    minimumHarvestSize: 7,
    attributeChemical: 3,
    attributeFood: 3,
    attributeDefensive: 3,
    attributeColor: 5,
    attributeWeed: 4,
    attributes: ["Light", "Shiny", "Crystal"],
    defaultDrop: "Glowstone Dust",
}));

CropData.registerCrop(makeGTCrop({
    name: "Fertilia",
    tier: 3,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 2,
    attributeFood: 3,
    attributeDefensive: 5,
    attributeColor: 4,
    attributeWeed: 8,
    attributes: ["Growth", "Healing", "Flower"],
    defaultDrop: "Calcite Dust",
    specialDrops: ["Fertilizer", "Apatite Dust", "Phosphate Dust"],
}));

CropData.registerCrop(makeGTCrop({
    name: "Bauxia",
    tier: 6,
    maxSize: 3,
    growthStageAfterHarvest: 2,
    minimumHarvestSize: 3,
    attributeChemical: 5,
    attributeFood: 0,
    attributeDefensive: 2,
    attributeColor: 3,
    attributeWeed: 3,
    attributes: ["Metal", "Aluminium", "Reed", "Aluminium"],
    foundationBlock: "Aluminium Block or Aluminium Ore",
    defaultDrop: "Bauxia Leaf",
}));

CropData.registerCrop(makeGTCrop({
    name: "Titania",
    tier: 9,
    maxSize: 3,
    growthStageAfterHarvest: 2,
    minimumHarvestSize: 3,
    attributeChemical: 5,
    attributeFood: 0,
    attributeDefensive: 3,
    attributeColor: 3,
    attributeWeed: 1,
    attributes: ["Metal", "Heavy", "Reed", "Titanium"],
    foundationBlock: "Titanium Block or Titanium Ore",
    defaultDrop: "Titania Leaf",
}));

CropData.registerCrop(makeGTCrop({
    name: "Reactoria",
    tier: 12,
    maxSize: 4,
    growthStageAfterHarvest: 2,
    minimumHarvestSize: 4,
    attributeChemical: 4,
    attributeFood: 0,
    attributeDefensive: 1,
    attributeColor: 2,
    attributeWeed: 1,
    attributes: ["Radioactive", "Metal", "Danger", "Uranium"],
    foundationBlock: "Uranium Block or Uranium Ore",
    defaultDrop: "Reactoria Leaf",
    specialDrops: ["Uranium Leaf"],
}));

CropData.registerCrop(makeGTCrop({
    name: "God of Thunder",
    tier: 9,
    maxSize: 4,
    growthStageAfterHarvest: 2,
    minimumHarvestSize: 4,
    attributeChemical: 3,
    attributeFood: 0,
    attributeDefensive: 5,
    attributeColor: 1,
    attributeWeed: 2,
    attributes: ["Radioactive", "Metal", "Coal", "Thorium"],
    foundationBlock: "Thorium Block or Thorium Ore",
    defaultDrop: "Thunder Leaf",
}));

CropData.registerCrop(makeGTCrop({
    name: "Transformium",
    tier: 12,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 6,
    attributeFood: 2,
    attributeDefensive: 1,
    attributeColor: 6,
    attributeWeed: 1,
    attributes: ["Transform", "Coal", "Reed"],
    defaultDrop: "UUA Berry",
    specialDrops: ["UUA Berry", "UUA Berry", "UUA Berry", "UUA Berry", "UUM Berry"],
}));

CropData.registerCrop(makeGTCrop({
    name: "Starwart",
    tier: 12,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 2,
    attributeFood: 0,
    attributeDefensive: 0,
    attributeColor: 1,
    attributeWeed: 0,
    attributes: ["Wither", "Nether", "Undead", "Netherstar"],
    foundationBlock: "Nether Star Block or Nether Star Ore",
    defaultDrop: "Coal Dust",
    specialDrops: [
        "Coal",
        "Skeleton Skull",
        "Wither Skeleton Skull",
        "Wither Skeleton Skull",
        "Nether Star Dust"
    ],
}));

CropData.registerCrop(makeGTCrop({
    name: "Zomplant",
    tier: 3,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 1,
    attributeFood: 3,
    attributeDefensive: 4,
    attributeColor: 2,
    attributeWeed: 6,
    attributes: ["Zombie", "Rotten", "Undead"],
    defaultDrop: "Rotten Flesh",
}));

CropData.registerCrop(makeGTCrop({
    name: "Nickelback",
    tier: 5,
    maxSize: 3,
    growthStageAfterHarvest: 2,
    minimumHarvestSize: 3,
    attributeChemical: 3,
    attributeFood: 0,
    attributeDefensive: 1,
    attributeColor: 2,
    attributeWeed: 2,
    attributes: ["Metal", "Fire", "Alloy"],
    foundationBlock: "Nickel Block or Nickel Ore",
    defaultDrop: "Nickelback Leaf",
}));

CropData.registerCrop(makeGTCrop({
    name: "Galvania",
    tier: 6,
    maxSize: 3,
    growthStageAfterHarvest: 2,
    minimumHarvestSize: 3,
    attributeChemical: 3,
    attributeFood: 0,
    attributeDefensive: 2,
    attributeColor: 2,
    attributeWeed: 3,
    attributes: ["Metal", "Alloy", "Bush"],
    foundationBlock: "Zinc Block or Zinc Ore",
    defaultDrop: "Galvania Leaf",
}));

CropData.registerCrop(makeGTCrop({
    name: "Evil Ore",
    tier: 8,
    maxSize: 4,
    growthStageAfterHarvest: 3,
    minimumHarvestSize: 4,
    attributeChemical: 4,
    attributeFood: 0,
    attributeDefensive: 2,
    attributeColor: 1,
    attributeWeed: 3,
    attributes: ["Crystal", "Fire", "Nether"],
    defaultDrop: "Nether Quartz Dust",
    specialDrops: ["Nether Quartz", "Certus Quartz Dust"],
}));

CropData.registerCrop(makeGTCrop({
    name: "Olivia",
    tier: 2,
    maxSize: 4,
    growthStageAfterHarvest: 3,
    minimumHarvestSize: 4,
    attributeChemical: 1,
    attributeFood: 0,
    attributeDefensive: 1,
    attributeColor: 4,
    attributeWeed: 0,
    attributes: ["Crystal", "Shiny", "Processing", "Olivine"],
    foundationBlock: "Olivine Block or Olivine Ore",
    defaultDrop: "Olivine Dust",
    specialDrops: ["Olivine"],
}));

CropData.registerCrop(makeGTCrop({
    name: "Sapphirum",
    tier: 4,
    maxSize: 4,
    growthStageAfterHarvest: 3,
    minimumHarvestSize: 4,
    attributeChemical: 1,
    attributeFood: 0,
    attributeDefensive: 1,
    attributeColor: 5,
    attributeWeed: 0,
    attributes: ["Crystal", "Shiny", "Metal", "Sapphire"],
    foundationBlock: "Sapphire Block or Sapphire Ore",
    defaultDrop: "Sapphire Dust",
    specialDrops: ["Sapphire"],
}));

CropData.registerCrop(makeGTCrop({
    name: "Pyrolusium",
    tier: 12,
    maxSize: 3,
    growthStageAfterHarvest: 2,
    minimumHarvestSize: 3,
    attributeChemical: 1,
    attributeFood: 0,
    attributeDefensive: 1,
    attributeColor: 1,
    attributeWeed: 0,
    attributes: ["Metal", "Clean", "Bush", "Manganese"],
    foundationBlock: "Manganese Block or Manganese Ore",
    defaultDrop: "Pyrolusium Leaf",
}));

CropData.registerCrop(makeGTCrop({
    name: "Scheelinium",
    tier: 12,
    maxSize: 3,
    growthStageAfterHarvest: 2,
    minimumHarvestSize: 3,
    attributeChemical: 3,
    attributeFood: 0,
    attributeDefensive: 1,
    attributeColor: 1,
    attributeWeed: 0,
    attributes: ["Metal", "Hard", "Bush", "Tungsten"],
    foundationBlock: "Tungsten Block or Tungsten Ore",
    defaultDrop: "Scheelinium Leaf",
}));

CropData.registerCrop(makeGTCrop({
    name: "Platina",
    tier: 11,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 3,
    attributeFood: 0,
    attributeDefensive: 0,
    attributeColor: 3,
    attributeWeed: 0,
    attributes: ["Metal", "Shiny", "Reed", "Platinum"],
    foundationBlock: "Platinum Block or Platinum Ore",
    defaultDrop: "Platina Leaf",
}));

CropData.registerCrop(makeGTCrop({
    name: "Quantaria",
    tier: 12,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 4,
    attributeFood: 0,
    attributeDefensive: 0,
    attributeColor: 1,
    attributeWeed: 0,
    attributes: ["Metal", "Iridium", "Reed"],
    foundationBlock: "Iridium Block or Iridium Ore",
    defaultDrop: "Quantaria Leaf (Iridium)",
    specialDrops: ["Quantaria Leaf (Osmium)"],
}));

CropData.registerCrop(makeGTCrop({
    name: "Stargatium",
    tier: 12,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 4,
    attributeFood: 0,
    attributeDefensive: 0,
    attributeColor: 2,
    attributeWeed: 0,
    attributes: ["Metal", "Heavy", "Alien", "Naquadah"],
    foundationBlock: "Naquadah Block or Naquadah Ore",
    defaultDrop: "Endstone Dust",
    specialDrops: ["Stargatium Leaf"],
}));

CropData.registerCrop(makeGTCrop({
    name: "Lemon",
    tier: 4,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 1,
    attributeFood: 1,
    attributeDefensive: 0,
    attributeColor: 2,
    attributeWeed: 0,
    attributes: ["Food", "Yellow", "Sour"],
    defaultDrop: "Lemon",
}));

CropData.registerCrop(makeGTCrop({
    name: "Chilly",
    tier: 4,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 1,
    attributeFood: 1,
    attributeDefensive: 0,
    attributeColor: 2,
    attributeWeed: 0,
    attributes: ["Food", "Red", "Spicy"],
    defaultDrop: "Chilly",
}));

CropData.registerCrop(makeGTCrop({
    name: "Tomato",
    tier: 4,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 1,
    attributeFood: 1,
    attributeDefensive: 0,
    attributeColor: 2,
    attributeWeed: 0,
    attributes: ["Food", "Red"],
    defaultDrop: "Tomato",
    specialDrops: ["Max Tomato"],
}));

CropData.registerCrop(makeGTCrop({
    name: "Grape",
    tier: 4,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 1,
    attributeFood: 1,
    attributeDefensive: 0,
    attributeColor: 2,
    attributeWeed: 0,
    attributes: ["Food", "Purple"],
    defaultDrop: "Grape",
}));

CropData.registerCrop(makeGTCrop({
    name: "Onion",
    tier: 4,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 1,
    attributeFood: 1,
    attributeDefensive: 0,
    attributeColor: 2,
    attributeWeed: 0,
    attributes: ["Food", "Brown"],
    defaultDrop: "Onion",
}));

CropData.registerCrop(makeGTCrop({
    name: "Cucumber",
    tier: 4,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 1,
    attributeFood: 1,
    attributeDefensive: 0,
    attributeColor: 2,
    attributeWeed: 0,
    attributes: ["Food", "Green"],
    defaultDrop: "Cucumber",
}));

CropData.registerCrop(makeGTCrop({
    name: "Tea",
    tier: 4,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 1,
    attributeFood: 1,
    attributeDefensive: 0,
    attributeColor: 2,
    attributeWeed: 0,
    attributes: ["Food", "Green", "Ingredient"],
    defaultDrop: "Tea Leaf",
}));

CropData.registerCrop(makeGTCrop({
    name: "Rape",
    tier: 4,
    maxSize: 4,
    growthStageAfterHarvest: 1,
    minimumHarvestSize: 4,
    attributeChemical: 1,
    attributeFood: 1,
    attributeDefensive: 0,
    attributeColor: 2,
    attributeWeed: 0,
    attributes: ["Food", "Yellow", "Oil"],
    defaultDrop: "Rape",
}));

CropData.registerCrop(makeGTCrop({
    name: "Micadia",
    tier: 9,
    maxSize: 3,
    growthStageAfterHarvest: 2,
    minimumHarvestSize: 3,
    attributeChemical: 2,
    attributeFood: 0,
    attributeDefensive: 3,
    attributeColor: 0,
    attributeWeed: 0,
    attributes: ["Metal", "Pine", "Mica", "Bush"],
    foundationBlock: "Mica Ore",
    defaultDrop: "Micadia Twig",
}));
