import { BiomeBonuses } from './CropMath.js';

export class BiomeData {
    /* Internal biome ID.
     */
    id: number = 0;

    /* Human-readable biome name.
     */
    name: string = "Unnamed Biome";

    /* Rainfall property of the biome,
     * also known as the biome's humidity.
     * NOT the same thing as IC2's humidity bonus.
     */
    rainfall: number = 0;

    /* Types that are applicable to this biome.
     */
    types: string[] = [];

    /* Internal class used to describe this biome.
     */
    class: string = "";

    static allBiomes: Map<string, BiomeData> = new Map<string, BiomeData>();

    /* These bonuses are defined by IC2 itself.
     */
    static nutrientBonus: Map<string, number> = new Map<string, number>([
        ["JUNGLE", 10],
        ["SWAMP", 10],
        ["MUSHROOM", 5],
        ["FOREST", 5],
        ["RIVER", 2],
        ["PLAINS", 0],
        ["SAVANNA", -2],
        ["HILLS", -5],
        ["MOUNTAIN", -5],
        ["WASTELAND", -8],
        ["END", -10],
        ["NETHER", -10],
        ["DEAD", -10],
    ]);

    /* This is defined in Crops++,
     * in src/main/java/com/github/bartimaeusnek/cropspp/BiomeHumidityBonus.java.
     */
    static humidityBonus: Map<string, number> = new Map<string, number>([
        ["HOT", -5],
        ["COLD", -5],
        ["SPARSE", -5],
        ["WET", 10],
        ["DRY", -10],
        ["SAVANNA", -5],
        ["CONIFEROUS", 7],
        ["JUNGLE", 10],
        ["SPOOKY", 7],
        ["DEAD", -5],
        ["LUSH", 7],
        ["NETHER", -10],
        ["END", -10],
        ["MUSHROOM", 8],
        ["MAGICAL", 6],
        ["OCEAN", 10],
        ["RIVER", 9],
        ["WATER", 10],
        ["MESA", -5],
        ["FOREST", 6],
        ["PLAINS", 0],
        ["MOUNTAIN", 5],
        ["HILLS", 4],
        ["SWAMP", 10],
        ["SANDY", -5],
        ["SNOWY", -5],
        ["WASTELAND", -5],
        ["BEACH", 6],
    ]);

    static computeBiomeBonuses(biome: BiomeData): BiomeBonuses {
        let nutrientBonus = 0;
        for(let type of biome.types) {
            if(BiomeData.nutrientBonus.has(type)) {
                nutrientBonus = Math.max(nutrientBonus, BiomeData.nutrientBonus.get(type)!);
            }
        }
        let humidityBonus = 0;
        for(let type of biome.types) {
            if(BiomeData.humidityBonus.has(type)) {
                humidityBonus = Math.max(humidityBonus, BiomeData.humidityBonus.get(type)!);
            }
        }
        return {nutrientBonus, humidityBonus};
    }
};

function registerBiomes(biomes: BiomeData[]) {
    for(let biome of biomes) {
        BiomeData.allBiomes.set(biome.name, biome);
    }
}

registerBiomes([
    {id: 0, name: "Ocean", rainfall: 0.5, types: ["OCEAN"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPOcean"},
    {id: 1, name: "Plains", rainfall: 0.4, types: ["PLAINS"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPPlains"},
    {id: 2, name: "Desert", rainfall: 0.0, types: ["HOT", "DRY", "SANDY"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPDesert"},
    {id: 3, name: "Extreme Hills", rainfall: 0.3, types: ["MOUNTAIN", "HILLS"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPExtremeHills"},
    {id: 4, name: "Forest", rainfall: 0.8, types: ["FOREST"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPForest"},
    {id: 5, name: "Taiga", rainfall: 0.8, types: ["COLD", "CONIFEROUS", "FOREST"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPTaiga"},
    {id: 6, name: "Swampland", rainfall: 0.9, types: ["WET", "SWAMP"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPSwamp"},
    {id: 7, name: "River", rainfall: 0.5, types: ["RIVER"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPRiver"},
    {id: 8, name: "Hell", rainfall: 0.0, types: ["HOT", "DRY", "NETHER"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPHell"},
    {id: 9, name: "Sky", rainfall: 0.5, types: ["COLD", "DRY", "END"], class: "chylex.hee.world.biome.BiomeGenHardcoreEnd"},
    {id: 10, name: "FrozenOcean", rainfall: 0.5, types: ["COLD", "OCEAN", "SNOWY"], class: "net.minecraft.world.biome.BiomeGenOcean"},
    {id: 11, name: "FrozenRiver", rainfall: 0.5, types: ["COLD", "RIVER", "SNOWY"], class: "net.minecraft.world.biome.BiomeGenRiver"},
    {id: 12, name: "Ice Plains", rainfall: 0.5, types: ["COLD", "SNOWY", "WASTELAND"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPIcePlains"},
    {id: 13, name: "Ice Mountains", rainfall: 0.5, types: ["COLD", "MOUNTAIN", "SNOWY"], class: "net.minecraft.world.biome.BiomeGenSnow"},
    {id: 14, name: "MushroomIsland", rainfall: 1.0, types: ["MUSHROOM"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPMushroomIsland"},
    {id: 15, name: "MushroomIslandShore", rainfall: 1.0, types: ["MUSHROOM", "BEACH"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPMushroomIsland"},
    {id: 16, name: "Beach", rainfall: 0.4, types: ["BEACH"], class: "net.minecraft.world.biome.BiomeGenBeach"},
    {id: 17, name: "DesertHills", rainfall: 0.0, types: ["HOT", "DRY", "HILLS", "SANDY"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPDesert"},
    {id: 18, name: "ForestHills", rainfall: 0.8, types: ["FOREST", "HILLS"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPForest"},
    {id: 19, name: "TaigaHills", rainfall: 0.8, types: ["COLD", "CONIFEROUS", "FOREST", "HILLS"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPTaiga"},
    {id: 20, name: "Extreme Hills Edge", rainfall: 0.3, types: ["MOUNTAIN"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPExtremeHills"},
    {id: 21, name: "Jungle", rainfall: 0.9, types: ["HOT", "DENSE", "WET", "JUNGLE"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPJungle"},
    {id: 22, name: "JungleHills", rainfall: 0.9, types: ["HOT", "DENSE", "WET", "JUNGLE", "HILLS"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPJungle"},
    {id: 23, name: "JungleEdge", rainfall: 0.8, types: ["HOT", "WET", "JUNGLE", "FOREST"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPJungle"},
    {id: 24, name: "Deep Ocean", rainfall: 0.5, types: ["OCEAN"], class: "net.minecraft.world.biome.BiomeGenOcean"},
    {id: 25, name: "Stone Beach", rainfall: 0.3, types: ["BEACH"], class: "net.minecraft.world.biome.BiomeGenStoneBeach"},
    {id: 26, name: "Cold Beach", rainfall: 0.3, types: ["COLD", "SNOWY", "BEACH"], class: "net.minecraft.world.biome.BiomeGenBeach"},
    {id: 27, name: "Birch Forest", rainfall: 0.6, types: ["FOREST"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPBirchForest"},
    {id: 28, name: "Birch Forest Hills", rainfall: 0.6, types: ["FOREST", "HILLS"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPBirchForest"},
    {id: 29, name: "Roofed Forest", rainfall: 0.8, types: ["DENSE", "SPOOKY", "FOREST"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPRoofedForest"},
    {id: 30, name: "Cold Taiga", rainfall: 0.4, types: ["COLD", "CONIFEROUS", "FOREST", "SNOWY"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPTaiga"},
    {id: 31, name: "Cold Taiga Hills", rainfall: 0.4, types: ["COLD", "CONIFEROUS", "FOREST", "HILLS", "SNOWY"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPTaiga"},
    {id: 32, name: "Mega Taiga", rainfall: 0.8, types: ["COLD", "CONIFEROUS", "FOREST"], class: "net.minecraft.world.biome.BiomeGenTaiga"},
    {id: 33, name: "Mega Taiga Hills", rainfall: 0.8, types: ["COLD", "CONIFEROUS", "FOREST", "HILLS"], class: "net.minecraft.world.biome.BiomeGenTaiga"},
    {id: 34, name: "Extreme Hills+", rainfall: 0.3, types: ["SPARSE", "FOREST", "MOUNTAIN"], class: "net.minecraft.world.biome.BiomeGenHills"},
    {id: 35, name: "Savanna", rainfall: 0.0, types: ["HOT", "SPARSE", "SAVANNA", "PLAINS"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPSavanna"},
    {id: 36, name: "Savanna Plateau", rainfall: 0.0, types: ["HOT", "SPARSE", "SAVANNA", "PLAINS"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPSavanna"},
    {id: 37, name: "Mesa", rainfall: 0.0, types: ["MESA", "SANDY"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPMesa"},
    {id: 38, name: "Mesa Plateau F", rainfall: 0.0, types: ["SPARSE", "MESA", "SANDY"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPMesa"},
    {id: 39, name: "Mesa Plateau", rainfall: 0.0, types: ["MESA", "SANDY"], class: "biomesoplenty.common.biome.overridden.BiomeGenBOPMesa"},
    {id: 40, name: "Alps Forest", rainfall: 0.5, types: ["COLD", "FOREST", "MOUNTAIN", "SNOWY"], class: "biomesoplenty.common.biome.overworld.sub.BiomeGenAlpsForest"},
    {id: 41, name: "Alps", rainfall: 0.5, types: ["COLD", "MOUNTAIN", "SNOWY"], class: "biomesoplenty.common.biome.overworld.BiomeGenAlps"},
    {id: 42, name: "Arctic", rainfall: 0.5, types: ["COLD", "DEAD", "SNOWY", "WASTELAND"], class: "biomesoplenty.common.biome.overworld.BiomeGenArctic"},
    {id: 43, name: "Bamboo Forest", rainfall: 0.9, types: ["DENSE", "JUNGLE", "LUSH", "FOREST"], class: "biomesoplenty.common.biome.overworld.BiomeGenBambooForest"},
    {id: 44, name: "Bayou", rainfall: 0.9, types: ["WET", "LUSH", "OCEAN", "RIVER", "SWAMP"], class: "biomesoplenty.common.biome.overworld.BiomeGenBayou"},
    {id: 45, name: "Bog", rainfall: 0.9, types: ["WET", "DEAD", "FOREST", "SWAMP"], class: "biomesoplenty.common.biome.overworld.BiomeGenBog"},
    {id: 47, name: "Boreal Forest", rainfall: 0.6, types: ["DENSE", "CONIFEROUS", "LUSH", "FOREST"], class: "biomesoplenty.common.biome.overworld.BiomeGenBorealForest"},
    {id: 48, name: "Brushland", rainfall: 0.1, types: ["HOT", "DRY", "SAVANNA", "PLAINS"], class: "biomesoplenty.common.biome.overworld.BiomeGenBrushland"},
    {id: 49, name: "Canyon", rainfall: 0.3, types: ["HOT", "SPARSE", "DRY", "MOUNTAIN", "HILLS", "SANDY"], class: "biomesoplenty.common.biome.overworld.BiomeGenCanyon"},
    {id: 50, name: "Canyon Ravine", rainfall: 0.3, types: ["HOT", "DRY", "HILLS", "SANDY"], class: "biomesoplenty.common.biome.overworld.sub.BiomeGenCanyonRavine"},
    {id: 51, name: "Chaparral", rainfall: 0.6, types: ["SPARSE", "PLAINS"], class: "biomesoplenty.common.biome.overworld.BiomeGenChaparral"},
    {id: 52, name: "Cherry Blossom Grove", rainfall: 0.8, types: ["LUSH", "MAGICAL", "FOREST"], class: "biomesoplenty.common.biome.overworld.BiomeGenCherryBlossomGrove"},
    {id: 53, name: "Coniferous Forest", rainfall: 0.5, types: ["DENSE", "CONIFEROUS", "FOREST", "HILLS"], class: "biomesoplenty.common.biome.overworld.BiomeGenConiferousForest"},
    {id: 54, name: "Coral Reef", rainfall: 0.9, types: ["OCEAN", "RIVER"], class: "biomesoplenty.common.biome.overworld.ocean.BiomeGenCoralReef"},
    {id: 56, name: "Crag", rainfall: 0.0, types: ["DRY", "SPOOKY", "DEAD", "MOUNTAIN", "WASTELAND"], class: "biomesoplenty.common.biome.overworld.BiomeGenCrag"},
    {id: 57, name: "Dead Forest", rainfall: 0.3, types: ["SPARSE", "SPOOKY", "DEAD", "FOREST"], class: "biomesoplenty.common.biome.overworld.BiomeGenDeadForest"},
    {id: 58, name: "Dead Swamp", rainfall: 0.9, types: ["SPARSE", "SPOOKY", "DEAD", "SWAMP"], class: "biomesoplenty.common.biome.overworld.BiomeGenDeadSwamp"},
    {id: 59, name: "Deciduous Forest", rainfall: 0.8, types: ["DENSE", "DRY", "FOREST"], class: "biomesoplenty.common.biome.overworld.BiomeGenDeciduousForest"},
    {id: 60, name: "Dry River", rainfall: 0.0, types: ["HOT", "DRY", "PLAINS", "SANDY"], class: "biomesoplenty.common.biome.overworld.tech.BiomeGenDryRiver"},
    {id: 61, name: "Eucalyptus Forest", rainfall: 1.0, types: ["HOT", "WET", "PLAINS"], class: "biomesoplenty.common.biome.overworld.BiomeGenEucalyptusForest"},
    {id: 62, name: "Fen", rainfall: 0.4, types: ["WET", "DEAD", "FOREST", "SWAMP"], class: "biomesoplenty.common.biome.overworld.BiomeGenFen"},
    {id: 63, name: "Flower Field", rainfall: 0.7, types: ["LUSH", "PLAINS"], class: "biomesoplenty.common.biome.overworld.BiomeGenFlowerField"},
    {id: 64, name: "Frost Forest", rainfall: 0.5, types: ["COLD", "SPARSE", "FOREST", "SNOWY"], class: "biomesoplenty.common.biome.overworld.BiomeGenFrostForest"},
    {id: 65, name: "Fungi Forest", rainfall: 1.0, types: ["WET", "LUSH", "MUSHROOM", "MAGICAL", "FOREST", "SWAMP"], class: "biomesoplenty.common.biome.overworld.BiomeGenFungiForest"},
    {id: 66, name: "Garden", rainfall: 0.8, types: ["LUSH", "MAGICAL", "PLAINS"], class: "biomesoplenty.common.biome.overworld.BiomeGenGarden"},
    {id: 67, name: "Glacier", rainfall: 0.2, types: ["COLD", "DEAD", "HILLS", "SNOWY"], class: "biomesoplenty.common.biome.overworld.sub.BiomeGenGlacier"},
    {id: 68, name: "Grassland", rainfall: 0.7, types: ["SPARSE", "LUSH", "PLAINS", "HILLS", "SWAMP"], class: "biomesoplenty.common.biome.overworld.BiomeGenGrassland"},
    {id: 69, name: "Grove", rainfall: 0.8, types: ["DENSE", "LUSH", "FOREST", "PLAINS"], class: "biomesoplenty.common.biome.overworld.BiomeGenGrove"},
    {id: 70, name: "Heathland", rainfall: 0.2, types: ["DRY", "SAVANNA", "PLAINS"], class: "biomesoplenty.common.biome.overworld.BiomeGenHeathland"},
    {id: 71, name: "Highland", rainfall: 0.8, types: ["SPARSE", "MOUNTAIN", "HILLS"], class: "biomesoplenty.common.biome.overworld.BiomeGenHighland"},
    {id: 72, name: "Jade Cliffs", rainfall: 0.9, types: ["DENSE", "FOREST", "MOUNTAIN"], class: "biomesoplenty.common.biome.overworld.BiomeGenJadeCliffs"},
    {id: 73, name: "Kelp Forest", rainfall: 0.9, types: ["OCEAN", "RIVER", "FOREST"], class: "biomesoplenty.common.biome.overworld.ocean.BiomeGenKelpForest"},
    {id: 74, name: "Land of Lakes", rainfall: 0.9, types: ["WET", "PLAINS"], class: "biomesoplenty.common.biome.overworld.BiomeGenLandOfLakes"},
    {id: 75, name: "Land of Lakes Marsh", rainfall: 0.9, types: ["WET", "SWAMP"], class: "biomesoplenty.common.biome.overworld.sub.BiomeGenLandOfLakesMarsh"},
    {id: 76, name: "Lavender Fields", rainfall: 0.7, types: ["SPARSE", "LUSH", "PLAINS"], class: "biomesoplenty.common.biome.overworld.BiomeGenLavenderFields"},
    {id: 77, name: "Lush Desert", rainfall: 0.5, types: ["HOT", "DRY", "SAVANNA", "LUSH", "SANDY"], class: "biomesoplenty.common.biome.overworld.BiomeGenLushDesert"},
    {id: 78, name: "Lush River", rainfall: 0.8, types: ["RIVER", "PLAINS"], class: "biomesoplenty.common.biome.overworld.tech.BiomeGenLushRiver"},
    {id: 79, name: "Lush Swamp", rainfall: 1.0, types: ["WET", "LUSH", "OCEAN", "RIVER", "SWAMP"], class: "biomesoplenty.common.biome.overworld.BiomeGenLushSwamp"},
    {id: 80, name: "Mangrove", rainfall: 0.9, types: ["WET", "LUSH", "OCEAN", "RIVER", "FOREST"], class: "biomesoplenty.common.biome.overworld.sub.BiomeGenMangrove"},
    {id: 81, name: "Maple Woods", rainfall: 0.8, types: ["COLD", "FOREST"], class: "biomesoplenty.common.biome.overworld.BiomeGenMapleWoods"},
    {id: 82, name: "Marsh", rainfall: 0.9, types: ["SPARSE", "WET", "LUSH", "OCEAN", "RIVER", "SWAMP"], class: "biomesoplenty.common.biome.overworld.BiomeGenMarsh"},
    {id: 83, name: "Meadow Forest", rainfall: 0.7, types: ["LUSH", "FOREST", "PLAINS"], class: "biomesoplenty.common.biome.overworld.sub.BiomeGenMeadowForest"},
    {id: 84, name: "Meadow", rainfall: 0.7, types: ["LUSH", "FOREST", "PLAINS"], class: "biomesoplenty.common.biome.overworld.BiomeGenMeadow"},
    {id: 85, name: "Moor", rainfall: 1.0, types: ["SPARSE", "WET", "HILLS", "SWAMP"], class: "biomesoplenty.common.biome.overworld.BiomeGenMoor"},
    {id: 86, name: "Mountain", rainfall: 0.1, types: ["DRY", "FOREST", "MOUNTAIN"], class: "biomesoplenty.common.biome.overworld.BiomeGenMountain"},
    {id: 87, name: "Mystic Grove", rainfall: 1.0, types: ["WET", "LUSH", "MAGICAL", "FOREST"], class: "biomesoplenty.common.biome.overworld.BiomeGenMysticGrove"},
    {id: 88, name: "Oasis", rainfall: 0.3, types: ["HOT", "DRY", "JUNGLE", "LUSH", "SANDY"], class: "biomesoplenty.common.biome.overworld.sub.BiomeGenOasis"},
    {id: 89, name: "Ominous Woods", rainfall: 0.9, types: ["SPOOKY", "DEAD", "MAGICAL", "FOREST", "SWAMP"], class: "biomesoplenty.common.biome.overworld.BiomeGenOminousWoods"},
    {id: 90, name: "Orchard", rainfall: 0.7, types: ["SPARSE", "LUSH", "FOREST", "PLAINS"], class: "biomesoplenty.common.biome.overworld.BiomeGenOrchard"},
    {id: 91, name: "Origin Valley", rainfall: 0.8, types: ["PLAINS"], class: "biomesoplenty.common.biome.overworld.BiomeGenOriginValley"},
    {id: 92, name: "Outback", rainfall: 0.05, types: ["HOT", "DRY", "SAVANNA", "PLAINS", "SANDY"], class: "biomesoplenty.common.biome.overworld.BiomeGenOutback"},
    {id: 94, name: "Polar Chasm", rainfall: 0.0, types: ["HOT", "DRY", "SAVANNA", "PLAINS"], class: "biomesoplenty.common.biome.nether.BiomeGenPolarChasm"},
    {id: 95, name: "Prairie", rainfall: 0.3, types: ["SPARSE", "DRY", "PLAINS"], class: "biomesoplenty.common.biome.overworld.BiomeGenPrairie"},
    {id: 96, name: "Quagmire", rainfall: 0.9, types: ["WET", "SPOOKY", "DEAD", "SWAMP", "WASTELAND"], class: "biomesoplenty.common.biome.overworld.sub.BiomeGenQuagmire"},
    {id: 97, name: "Rainforest", rainfall: 1.0, types: ["DENSE", "WET", "JUNGLE", "LUSH", "FOREST", "HILLS"], class: "biomesoplenty.common.biome.overworld.BiomeGenRainforest"},
    {id: 98, name: "Redwood Forest", rainfall: 0.7, types: ["DENSE", "CONIFEROUS", "FOREST"], class: "biomesoplenty.common.biome.overworld.BiomeGenRedwoodForest"},
    {id: 99, name: "Sacred Springs", rainfall: 0.5, types: ["DENSE", "WET", "LUSH", "MAGICAL", "FOREST", "MOUNTAIN"], class: "biomesoplenty.common.biome.overworld.BiomeGenSacredSprings"},
    {id: 100, name: "Scrubland", rainfall: 0.0, types: ["HOT", "SPARSE", "DRY", "SAVANNA", "PLAINS"], class: "biomesoplenty.common.biome.overworld.sub.BiomeGenScrubland"},
    {id: 101, name: "Seasonal Forest Clearing", rainfall: 0.8, types: ["PLAINS"], class: "biomesoplenty.common.biome.overworld.sub.BiomeGenSeasonalForestClearing"},
    {id: 102, name: "Seasonal Forest", rainfall: 0.8, types: ["DENSE", "LUSH", "FOREST"], class: "biomesoplenty.common.biome.overworld.BiomeGenSeasonalForest"},
    {id: 103, name: "Shield", rainfall: 0.8, types: ["WET", "CONIFEROUS", "OCEAN", "RIVER", "FOREST"], class: "biomesoplenty.common.biome.overworld.BiomeGenShield"},
    {id: 104, name: "Shrubland", rainfall: 0.05, types: ["SPARSE", "DRY", "PLAINS"], class: "biomesoplenty.common.biome.overworld.BiomeGenShrubland"},
    {id: 105, name: "Silkglades", rainfall: 0.9, types: ["SPOOKY", "DEAD", "FOREST", "SWAMP"], class: "biomesoplenty.common.biome.overworld.sub.BiomeGenSilkglades"},
    {id: 106, name: "Sludgepit", rainfall: 0.9, types: ["WET", "SPOOKY", "DEAD", "FOREST", "SWAMP", "WASTELAND"], class: "biomesoplenty.common.biome.overworld.BiomeGenSludgepit"},
    {id: 107, name: "Snowy Coniferous Forest", rainfall: 0.5, types: ["COLD", "DENSE", "CONIFEROUS", "FOREST", "HILLS", "SNOWY"], class: "biomesoplenty.common.biome.overworld.BiomeGenConiferousForestSnow"},
    {id: 108, name: "Spectral Garden", rainfall: 0.0, types: ["HOT", "DRY", "SAVANNA", "PLAINS"], class: "biomesoplenty.common.biome.end.BiomeGenSpectralGarden"},
    {id: 109, name: "Spruce Woods", rainfall: 0.8, types: ["DENSE", "CONIFEROUS", "LUSH", "FOREST"], class: "biomesoplenty.common.biome.overworld.sub.BiomeGenSpruceWoods"},
    {id: 110, name: "Steppe", rainfall: 0.05, types: ["HOT", "SPARSE", "DRY", "SAVANNA", "DEAD", "PLAINS", "SANDY"], class: "biomesoplenty.common.biome.overworld.BiomeGenSteppe"},
    {id: 111, name: "Temperate Rainforest", rainfall: 1.2, types: ["WET", "CONIFEROUS", "LUSH", "FOREST", "HILLS"], class: "biomesoplenty.common.biome.overworld.BiomeGenTemperateRainforest"},
    {id: 112, name: "Thicket", rainfall: 0.2, types: ["DENSE", "DRY", "DEAD", "FOREST", "PLAINS"], class: "biomesoplenty.common.biome.overworld.BiomeGenThicket"},
    {id: 113, name: "Tropical Rainforest", rainfall: 1.0, types: ["HOT", "DENSE", "WET", "JUNGLE", "LUSH"], class: "biomesoplenty.common.biome.overworld.BiomeGenTropicalRainforest"},
    {id: 114, name: "Tropics", rainfall: 1.0, types: ["WET", "JUNGLE", "LUSH", "OCEAN", "RIVER", "BEACH"], class: "biomesoplenty.common.biome.overworld.sub.BiomeGenTropics"},
    {id: 115, name: "Tundra", rainfall: 0.5, types: ["COLD", "SPARSE", "DRY", "DEAD", "WASTELAND"], class: "biomesoplenty.common.biome.overworld.BiomeGenTundra"},
    {id: 117, name: "Visceral Heap", rainfall: 0.0, types: ["SPOOKY", "NETHER"], class: "biomesoplenty.common.biome.nether.BiomeGenVisceralHeap"},
    {id: 118, name: "Volcano", rainfall: 0.05, types: ["HOT", "DRY", "MOUNTAIN", "WASTELAND"], class: "biomesoplenty.common.biome.overworld.sub.BiomeGenVolcano"},
    {id: 119, name: "Wasteland", rainfall: 0.05, types: ["SPARSE", "SPOOKY", "DEAD", "WASTELAND"], class: "biomesoplenty.common.biome.overworld.BiomeGenWasteland"},
    {id: 120, name: "Wetland", rainfall: 0.9, types: ["DENSE", "WET", "LUSH", "FOREST", "SWAMP"], class: "biomesoplenty.common.biome.overworld.BiomeGenWetland"},
    {id: 121, name: "Woodland", rainfall: 0.4, types: ["DENSE", "DRY", "FOREST"], class: "biomesoplenty.common.biome.overworld.BiomeGenWoodland"},
    {id: 122, name: "Xeric Shrubland", rainfall: 0.2, types: ["HOT", "PLAINS", "SANDY"], class: "biomesoplenty.common.biome.overworld.BiomeGenXericShrubland"},
    {id: 123, name: "Dense Forest", rainfall: 0.7, types: ["PLAINS"], class: "biomesoplenty.common.biome.overworld.BiomeGenDenseForest"},
    {id: 126, name: "Ocean Oil Field", rainfall: 0.5, types: ["OCEAN", "RIVER"], class: "buildcraft.energy.worldgen.BiomeGenOilOcean"},
    {id: 127, name: "Desert Oil Field", rainfall: 0.0, types: ["SANDY"], class: "buildcraft.energy.worldgen.BiomeGenOilDesert"},
    {id: 128, name: "Boneyard", rainfall: 0.0, types: ["SPOOKY", "NETHER", "WASTELAND"], class: "biomesoplenty.common.biome.nether.BiomeGenBoneyard"},
    {id: 129, name: "Sunflower Plains", rainfall: 0.4, types: ["PLAINS"], class: "net.minecraft.world.biome.BiomeGenPlains"},
    {id: 130, name: "Desert M", rainfall: 0.0, types: ["HOT", "DRY", "PLAINS", "SANDY"], class: "net.minecraft.world.biome.BiomeGenMutated"},
    {id: 131, name: "Extreme Hills M", rainfall: 0.3, types: ["HILLS"], class: "net.minecraft.world.biome.BiomeGenHills"},
    {id: 132, name: "Flower Forest", rainfall: 0.8, types: ["FOREST", "HILLS"], class: "net.minecraft.world.biome.BiomeGenForest"},
    {id: 133, name: "Taiga M", rainfall: 0.8, types: ["HILLS"], class: "net.minecraft.world.biome.BiomeGenMutated"},
    {id: 134, name: "Swampland M", rainfall: 0.9, types: ["WET", "SWAMP"], class: "net.minecraft.world.biome.BiomeGenMutated"},
    {id: 135, name: "Storage Cell", rainfall: 0.5, types: ["COLD", "PLAINS"], class: "appeng.spatial.BiomeGenStorage"},
    {id: 136, name: "Corrupted Sands", rainfall: 0.0, types: ["SPOOKY", "NETHER", "SANDY"], class: "biomesoplenty.common.biome.nether.BiomeGenCorruptedSands"},
    {id: 137, name: "Phantasmagoric Inferno", rainfall: 0.0, types: ["SPOOKY", "NETHER"], class: "biomesoplenty.common.biome.nether.BiomeGenPhantasmagoricInferno"},
    {id: 138, name: "Undergarden", rainfall: 0.0, types: ["JUNGLE", "SPOOKY", "NETHER"], class: "biomesoplenty.common.biome.nether.BiomeGenUndergarden"},
    {id: 140, name: "Ice Plains Spikes", rainfall: 0.5, types: ["COLD", "HILLS", "SNOWY"], class: "net.minecraft.world.biome.BiomeGenSnow"},
    {id: 141, name: "moon", rainfall: 0.0, types: ["COLD", "DRY", "DEAD"], class: "micdoodle8.mods.galacticraft.core.world.gen.BiomeGenFlatMoon"},
    {id: 142, name: "marsFlat", rainfall: 0.0, types: ["COLD", "DRY", "DEAD", "SANDY"], class: "micdoodle8.mods.galacticraft.planets.mars.world.gen.BiomeGenFlatMars"},
    {id: 143, name: "asteroids", rainfall: 0.0, types: ["COLD", "DRY", "SPOOKY", "DEAD"], class: "micdoodle8.mods.galacticraft.planets.asteroids.world.gen.BiomeGenBaseAsteroids"},
    {id: 149, name: "Jungle M", rainfall: 0.9, types: ["HOT", "WET", "HILLS"], class: "net.minecraft.world.biome.BiomeGenMutated"},
    {id: 151, name: "JungleEdge M", rainfall: 0.8, types: ["HOT", "HILLS"], class: "net.minecraft.world.biome.BiomeGenMutated"},
    {id: 155, name: "Birch Forest M", rainfall: 0.6, types: ["HILLS"], class: "null"},
    {id: 156, name: "Birch Forest Hills M", rainfall: 0.6, types: ["HILLS"], class: "null"},
    {id: 157, name: "Roofed Forest M", rainfall: 0.8, types: ["HILLS"], class: "null"},
    {id: 158, name: "Cold Taiga M", rainfall: 0.4, types: ["COLD", "HILLS", "SNOWY"], class: "net.minecraft.world.biome.BiomeGenMutated"},
    {id: 160, name: "Mega Spruce Taiga", rainfall: 0.8, types: ["DENSE", "FOREST"], class: "net.minecraft.world.biome.BiomeGenTaiga"},
    {id: 161, name: "Mega Spruce Taiga", rainfall: 0.8, types: ["DENSE", "FOREST"], class: "net.minecraft.world.biome.BiomeGenTaiga"},
    {id: 162, name: "Extreme Hills+ M", rainfall: 0.3, types: ["HILLS"], class: "net.minecraft.world.biome.BiomeGenHills"},
    {id: 163, name: "Savanna M", rainfall: 0.0, types: ["HOT", "SPARSE", "DRY", "SAVANNA", "HILLS"], class: "net.minecraft.world.biome.BiomeGenSavanna$Mutated"},
    {id: 164, name: "Savanna Plateau M", rainfall: 0.0, types: ["HOT", "SPARSE", "DRY", "SAVANNA", "HILLS"], class: "net.minecraft.world.biome.BiomeGenSavanna$Mutated"},
    {id: 165, name: "Mesa (Bryce)", rainfall: 0.0, types: ["HOT", "DRY", "PLAINS", "SANDY"], class: "net.minecraft.world.biome.BiomeGenMesa"},
    {id: 166, name: "Mesa Plateau F M", rainfall: 0.0, types: ["HOT", "DRY", "FOREST", "SANDY"], class: "net.minecraft.world.biome.BiomeGenMesa"},
    {id: 167, name: "Mesa Plateau M", rainfall: 0.0, types: ["HOT", "DRY", "PLAINS", "SANDY"], class: "net.minecraft.world.biome.BiomeGenMesa"},
    {id: 170, name: "Twilight Clearing", rainfall: 0.4, types: ["SPARSE", "PLAINS"], class: "twilightforest.biomes.TFBiomeClearing"},
    {id: 171, name: "Dark Forest", rainfall: 0.8, types: ["DENSE", "SPOOKY", "FOREST"], class: "twilightforest.biomes.TFBiomeDarkForest"},
    {id: 172, name: "Dark Forest Center", rainfall: 0.8, types: ["DENSE", "SPOOKY", "MAGICAL", "FOREST"], class: "twilightforest.biomes.TFBiomeDarkForestCenter"},
    {id: 173, name: "Deep Mushroom Forest", rainfall: 1.0, types: ["MUSHROOM", "FOREST"], class: "twilightforest.biomes.TFBiomeDeepMushrooms"},
    {id: 175, name: "Fire Swamp", rainfall: 0.4, types: ["HOT", "SWAMP", "WASTELAND"], class: "twilightforest.biomes.TFBiomeFireSwamp"},
    {id: 176, name: "Twilight Glacier", rainfall: 0.1, types: ["COLD", "SNOWY", "WASTELAND"], class: "twilightforest.biomes.TFBiomeGlacier"},
    {id: 177, name: "Twilight Highlands", rainfall: 0.7, types: ["CONIFEROUS", "FOREST", "MOUNTAIN"], class: "twilightforest.biomes.TFBiomeHighlands"},
    {id: 178, name: "Highlands Center", rainfall: 0.2, types: ["DRY", "DEAD", "MESA", "WASTELAND"], class: "twilightforest.biomes.TFBiomeFinalPlateau"},
    {id: 179, name: "Twilight Lake", rainfall: 1.0, types: ["OCEAN"], class: "twilightforest.biomes.TFBiomeTwilightLake"},
    {id: 180, name: "Firefly Forest", rainfall: 1.0, types: ["LUSH", "FOREST"], class: "twilightforest.biomes.TFBiomeFireflyForest"},
    {id: 181, name: "Mushroom Forest", rainfall: 0.8, types: ["MUSHROOM", "FOREST"], class: "twilightforest.biomes.TFBiomeMushrooms"},
    {id: 182, name: "Oak Savanna", rainfall: 0.0, types: ["SPARSE", "FOREST"], class: "twilightforest.biomes.TFBiomeOakSavanna"},
    {id: 184, name: "Twilight Stream", rainfall: 1.0, types: ["RIVER"], class: "twilightforest.biomes.TFBiomeStream"},
    {id: 185, name: "Twilight Swamp", rainfall: 0.9, types: ["WET", "SWAMP"], class: "twilightforest.biomes.TFBiomeSwamp"},
    {id: 186, name: "Thornlands", rainfall: 0.2, types: ["DRY", "DEAD", "HILLS", "WASTELAND"], class: "twilightforest.biomes.TFBiomeThornlands"},
    {id: 187, name: "Twilight Forest", rainfall: 0.5, types: ["FOREST"], class: "twilightforest.biomes.TFBiomeTwilightForest"},
    {id: 188, name: "Dense Twilight Forest", rainfall: 0.8, types: ["DENSE", "FOREST"], class: "twilightforest.biomes.TFBiomeTwilightForestVariant"},
    {id: 189, name: "Enchanted Forest", rainfall: 0.5, types: ["MAGICAL", "FOREST"], class: "twilightforest.biomes.TFBiomeEnchantedForest"},
    {id: 190, name: "Eerie", rainfall: 0.5, types: ["SPOOKY", "MAGICAL"], class: "thaumcraft.common.lib.world.biomes.BiomeGenEerie"},
    {id: 191, name: "Eldritch", rainfall: 0.5, types: ["SPOOKY", "END", "MAGICAL"], class: "thaumcraft.common.lib.world.biomes.BiomeGenEldritch"},
    {id: 192, name: "Magical Forest", rainfall: 0.6, types: ["MAGICAL", "FOREST"], class: "thaumcraft.common.lib.world.biomes.BiomeGenMagicalForest"},
    {id: 193, name: "Tainted Land", rainfall: 0.5, types: ["MAGICAL", "WASTELAND"], class: "thaumcraft.common.lib.world.biomes.BiomeGenTaint"},
    {id: 196, name: "Snowy Forest", rainfall: 0.9, types: ["COLD", "CONIFEROUS", "FOREST", "SNOWY"], class: "twilightforest.biomes.TFBiomeSnow"},
    {id: 199, name: "Toxic Everglades", rainfall: 0.7, types: ["DENSE", "DEAD", "FOREST", "HILLS"], class: "gtPlusPlus.everglades.biome.Biome_Everglades.BiomeGenEverglades"},
    {id: 200, name: "rwg_riverIce", rainfall: 0.1, types: ["COLD", "RIVER", "SNOWY"], class: "rwg.biomes.base.BaseBiomeRiver"},
    {id: 201, name: "Space", rainfall: 0.0, types: ["COLD", "DRY", "SPOOKY", "DEAD"], class: "galaxyspace.core.world.biome.BiomeGenSpaceGS"},
    {id: 202, name: "rwg_riverCold", rainfall: 0.4, types: ["COLD", "CONIFEROUS", "RIVER", "FOREST"], class: "rwg.biomes.base.BaseBiomeRiver"},
    {id: 203, name: "Venus", rainfall: 0.0, types: ["COLD", "DRY", "SPOOKY", "DEAD"], class: "galaxyspace.SolarSystem.planets.venus.world.biome.BiomeGenVenus"},
    {id: 204, name: "Pluto", rainfall: 0.0, types: ["COLD", "DRY", "SPOOKY", "DEAD"], class: "galaxyspace.SolarSystem.planets.pluto.world.biome.BiomeGenPluto"},
    {id: 205, name: "rwg_riverTemperate", rainfall: 0.6, types: ["COLD", "RIVER", "FOREST"], class: "rwg.biomes.base.BaseBiomeRiver"},
    {id: 206, name: "Pluto2", rainfall: 0.0, types: ["COLD", "DRY", "SPOOKY", "DEAD"], class: "galaxyspace.SolarSystem.planets.pluto.world.biome.BiomeGenPluto1"},
    {id: 207, name: "rwg_riverHot", rainfall: 0.2, types: ["HOT", "DRY", "RIVER", "SANDY"], class: "rwg.biomes.base.BaseBiomeRiver"},
    {id: 208, name: "Pluto3", rainfall: 0.0, types: ["COLD", "DRY", "SPOOKY", "DEAD"], class: "galaxyspace.SolarSystem.planets.pluto.world.biome.BiomeGenPluto2"},
    {id: 209, name: "rwg_riverWet", rainfall: 0.9, types: ["HOT", "WET", "JUNGLE", "RIVER"], class: "rwg.biomes.base.BaseBiomeRiver"},
    {id: 210, name: "Pluto4", rainfall: 0.0, types: ["COLD", "DRY", "SPOOKY", "DEAD"], class: "galaxyspace.SolarSystem.planets.pluto.world.biome.BiomeGenPluto4"},
    {id: 211, name: "rwg_riverOasis", rainfall: 0.9, types: ["HOT", "WET", "JUNGLE", "RIVER"], class: "rwg.biomes.base.BaseBiomeRiver"},
    {id: 212, name: "Kuiper Belt", rainfall: 0.0, types: ["COLD", "DRY", "SPOOKY", "DEAD"], class: "galaxyspace.SolarSystem.planets.kuiperbelt.world.BiomeGenBaseKuiper"},
    {id: 213, name: "rwg_oceanIce", rainfall: 0.1, types: ["COLD", "OCEAN", "SNOWY", "BEACH"], class: "rwg.biomes.base.BaseBiomeOcean"},
    {id: 214, name: "rwg_oceanCold", rainfall: 0.4, types: ["COLD", "CONIFEROUS", "OCEAN", "FOREST", "BEACH"], class: "rwg.biomes.base.BaseBiomeOcean"},
    {id: 215, name: "Io", rainfall: 0.0, types: ["COLD", "DRY", "SPOOKY", "DEAD"], class: "galaxyspace.SolarSystem.moons.io.world.biome.BiomeGenIo"},
    {id: 216, name: "rwg_oceanTemperate", rainfall: 0.6, types: ["COLD", "OCEAN", "FOREST", "BEACH"], class: "rwg.biomes.base.BaseBiomeOcean"},
    {id: 217, name: "IoAsh", rainfall: 0.0, types: ["COLD", "DRY", "SPOOKY", "DEAD"], class: "galaxyspace.SolarSystem.moons.io.world.biome.BiomeGenIoAsh"},
    {id: 218, name: "rwg_oceanHot", rainfall: 0.2, types: ["HOT", "DRY", "OCEAN", "SANDY", "BEACH"], class: "rwg.biomes.base.BaseBiomeOcean"},
    {id: 219, name: "Titan", rainfall: 0.0, types: ["COLD", "DRY", "SPOOKY", "DEAD"], class: "galaxyspace.SolarSystem.moons.titan.world.biome.BiomeGenTitan"},
    {id: 220, name: "BarnardaCShores", rainfall: 0.0, types: ["COLD", "DRY", "SPOOKY", "DEAD"], class: "galaxyspace.BarnardsSystem.planets.barnardaC.world.biome.BiomeGenBarnardaC"},
    {id: 221, name: "BarnardaCHills", rainfall: 0.0, types: ["COLD", "DRY", "SPOOKY", "DEAD"], class: "galaxyspace.BarnardsSystem.planets.barnardaC.world.biome.BiomeGenBarnardaCHills"},
    {id: 222, name: "BarnardaCLowPlains", rainfall: 0.0, types: ["COLD", "DRY", "SPOOKY", "DEAD"], class: "galaxyspace.BarnardsSystem.planets.barnardaC.world.biome.BiomeGenBarnardaCLowPlains"},
    {id: 223, name: "rwg_oceanOasis", rainfall: 0.9, types: ["HOT", "WET", "JUNGLE", "OCEAN", "BEACH"], class: "rwg.biomes.base.BaseBiomeOcean"},
    {id: 224, name: "rwg_snowDesert", rainfall: 0.1, types: ["COLD", "SNOWY", "WASTELAND"], class: "rwg.biomes.base.BaseBiomeSnowDesert"},
    {id: 225, name: "rwg_snowForest", rainfall: 0.1, types: ["COLD", "CONIFEROUS", "FOREST", "SNOWY"], class: "rwg.biomes.base.BaseBiomeSnowForest"},
    {id: 226, name: "rwg_coldPlains", rainfall: 0.2, types: ["COLD", "WASTELAND"], class: "rwg.biomes.base.BaseBiomeColdPlains"},
    {id: 227, name: "rwg_coldForest", rainfall: 0.4, types: ["COLD", "DENSE", "CONIFEROUS", "FOREST", "HILLS"], class: "rwg.biomes.base.BaseBiomeColdForest"},
    {id: 228, name: "rwg_hotPlains", rainfall: 0.1, types: ["HOT", "SPARSE", "SAVANNA", "PLAINS"], class: "rwg.biomes.base.BaseBiomeHotPlains"},
    {id: 229, name: "rwg_hotForest", rainfall: 0.2, types: ["HOT", "SPARSE", "SAVANNA", "PLAINS"], class: "rwg.biomes.base.BaseBiomeHotForest"},
    {id: 230, name: "rwg_hotDesert", rainfall: 0.0, types: ["HOT", "DRY", "SANDY"], class: "rwg.biomes.base.BaseBiomeHotDesert"},
    {id: 231, name: "rwg_plains", rainfall: 0.4, types: ["PLAINS"], class: "rwg.biomes.base.BaseBiomePlains"},
    {id: 232, name: "rwg_tropical", rainfall: 0.8, types: ["HOT", "WET", "JUNGLE"], class: "rwg.biomes.base.BaseBiomeTropicalIsland"},
    {id: 233, name: "rwg_redwood", rainfall: 0.6, types: ["COLD", "CONIFEROUS", "FOREST"], class: "rwg.biomes.base.BaseBiomeRedwood"},
    {id: 234, name: "rwg_jungle", rainfall: 0.9, types: ["HOT", "WET", "JUNGLE"], class: "rwg.biomes.base.BaseBiomeJungle"},
    {id: 235, name: "rwg_oasis", rainfall: 0.9, types: ["HOT", "WET", "PLAINS"], class: "rwg.biomes.base.BaseBiomeRiver"},
    {id: 236, name: "rwg_temperateForest", rainfall: 0.6, types: ["PLAINS"], class: "rwg.biomes.base.BaseBiomeTemperateForest"},
    {id: 237, name: "rwg_oceanWet", rainfall: 0.9, types: ["HOT", "WET", "JUNGLE", "OCEAN", "BEACH"], class: "rwg.biomes.base.BaseBiomeOcean"},
    {id: 238, name: "BarnardaCFlowers", rainfall: 0.0, types: ["COLD", "DRY", "SPOOKY", "DEAD"], class: "galaxyspace.BarnardsSystem.planets.barnardaC.world.biome.BiomeGenBarnardaCFlowers"},
    {id: 239, name: "BarnardaCOceans", rainfall: 0.0, types: ["COLD", "DENSE", "DRY", "SPOOKY", "DEAD", "FOREST", "HILLS"], class: "galaxyspace.BarnardsSystem.planets.barnardaC.world.biome.BiomeGenBarnardaCOceans"},
    {id: 240, name: "Australian Desert II", rainfall: 0.1, types: ["DENSE", "DRY", "FOREST"], class: "gtPlusPlus.australia.biome.type.Biome_AustralianDesert2.BiomeGenAustralianDesert2"},
    {id: 241, name: "Australian Desert III", rainfall: 0.0, types: ["HOT", "SPARSE", "DRY", "PLAINS", "SANDY"], class: "gtPlusPlus.australia.biome.type.Biome_AustralianDesert_Ex"},
    {id: 242, name: "Plainlands", rainfall: 0.4, types: ["SPARSE", "DRY", "PLAINS"], class: "gtPlusPlus.australia.biome.type.Biome_AustralianPlains"},
    {id: 243, name: "Australian Outback", rainfall: 0.0, types: ["HOT", "SPARSE", "DRY", "FOREST", "SANDY"], class: "gtPlusPlus.australia.biome.type.Biome_AustralianOutback"},
    {id: 244, name: "Australian Ocean", rainfall: 0.5, types: ["COLD", "SPARSE", "OCEAN", "PLAINS"], class: "gtPlusPlus.australia.biome.type.Biome_AustralianOcean"},
    {id: 245, name: "Australian Forest", rainfall: 0.75, types: ["HOT", "DENSE", "FOREST"], class: "gtPlusPlus.australia.biome.type.Biome_AustralianForest"},
    {id: 255, name: "TCetiE", rainfall: 0.0, types: ["COLD", "DRY", "SPOOKY", "DEAD"], class: "galaxyspace.TCetiSystem.planets.tcetiE.world.biome.BiomeGenTCetiE"},
]);
